"""
Configuration file for AI Medical Reporting System
Centralized settings for API URLs, prompts, and UI parameters
"""

# API Configuration
API_URL = "https://a5b9c23d9648.ngrok-free.app"  # AI Reporting API URL
CLASSIFICATION_API_URL = "http://localhost:5002"  # MAZIK Classification API URL

# Classification Settings
ENABLE_CLASSIFICATION = True  # Enable pre-classification before reporting
CLASSIFICATION_TIMEOUT = 30  # Timeout in seconds for each classification request
AUTO_CLASSIFY = True  # Automatically determine model type (brain vs mammography)

# AI Reporting Settings
DEFAULT_ROLE_INSTRUCTION = """You are an expert radiologist analyzing medical images. 
Provide detailed, professional medical assessments based on the images and any pre-classification results provided.
Consider the classification model's predictions as preliminary findings and provide your expert interpretation."""

MAX_TOKENS_DEFAULT = 2048
MAX_TOKENS_MIN = 512
MAX_TOKENS_MAX = 4096

# Default Prompts
DEFAULT_PROMPT_PNG = """Please provide a comprehensive medical assessment of the image(s), including:

1. **Image Quality Assessment:** Evaluate the technical quality of the images
2. **Anatomical Findings:** Describe visible anatomical structures
3. **Pathological Findings:** Identify any abnormalities or pathology
4. **Correlation with Classification:** Compare your findings with the pre-classification results
5. **Differential Diagnosis:** Provide possible diagnoses ranked by likelihood
6. **Clinical Recommendations:** Suggest next steps for patient management
7. **Additional Comments:** Any other relevant observations

Please provide a detailed, structured report."""

DEFAULT_PROMPT_DICOM = """Please analyze this medical imaging study comprehensively:

1. **Study Overview:** Describe the imaging modality and study type
2. **Image Quality:** Assess technical quality and diagnostic adequacy
3. **Anatomical Assessment:** Systematic review of visible structures
4. **Pathological Findings:** Detailed description of any abnormalities
5. **Correlation with Classification:** Compare findings with pre-classification results
6. **Differential Diagnosis:** Ranked list of possible diagnoses with reasoning
7. **Comparison:** If applicable, compare with prior studies
8. **Clinical Recommendations:** Management and follow-up suggestions
9. **Impression:** Concise summary of key findings

Provide a detailed radiological report following standard medical imaging reporting guidelines."""

# UI Configuration
PAGE_TITLE = "AI Medical Reporting System"
PAGE_ICON = "🏥"
LAYOUT = "wide"

# PDF Settings
PDF_HEADER_TEXT = "AI Medical Imaging Report"
PDF_FOOTER_TEXT = "Generated by AI Medical Reporting System"
PDF_INCLUDE_IMAGES = True
PDF_INCLUDE_CLASSIFICATION = True

# Footer
FOOTER_TEXT = """<div style='text-align: center; color: #666; padding: 2rem;'>
<p>AI Medical Reporting System - Powered by Advanced Medical AI</p>
<p style='font-size: 0.8rem;'>This system integrates classification and reporting models for comprehensive medical image analysis</p>
</div>"""

# Model Information
CLASSIFICATION_MODELS = {
    'brain_tumor': {
        'name': 'MAZIK Brain Tumor Classifier',
        'classes': ['Brain_Glioma', 'Brain_Meningioma', 'Brain_NoTumor', 'Brain_Pituitary'],
        'confidence_threshold': 0.8
    },
    'mammography': {
        'name': 'MAZIK Mammography Classifier',
        'classes': ['Breast_Benign', 'Breast_Malignant', 'Breast_Benign_Without_Callback'],
        'confidence_threshold': 0.8
    }
}

# Advanced Settings
SHOW_ADVANCED_SETTINGS = True
SHOW_CLASSIFICATION_DETAILS = True
ENABLE_PDF_DOWNLOAD = True
ENABLE_MARKDOWN_DOWNLOAD = True

